### ISSUE TITLE
Not working in Webstorm 2018.3.4

### ISSUE THREAD

**Issue by poppabear8883** [interfaced/brightscript-intellij-plugin#11]
![image](https://user-images.githubusercontent.com/7263458/53289699-4af15580-3767-11e9-8000-c7e1f5cdd56c.png)

`When opening the project it throws an indexing error (see below)`
![image](https://user-images.githubusercontent.com/7263458/53289719-a7547500-3767-11e9-8f80-6b8b679216ec.png)

`When opening a file it just continues to try and load (see below)`
![image](https://user-images.githubusercontent.com/7263458/53289701-5b093500-3767-11e9-8955-c36e14ec8106.png)

Please advise ASAP!

Thanks

**Comment by reeFridge** [comment]
@poppabear8883 Thanks for the report! I Am examined the problem, it happens because in code of `Highlighter` class for our plugin we using class which depends on Java language support. New version of plugin with fixes in queue on release. You can check it before release in plugin repo, manually installed new version of plugin from file. Latest version of plugin could be found on releases page of this repo.

**Comment by reeFridge** [comment]
resolved
